services:
  # SERVIÇO 1: BANCO DE DADOS (Intacto)
  db:
    image: mysql:8.0
    container_name: vidaplus-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vidaplus_db
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: user_dev
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2G

  # SERVIÇO 2: SUA APLICAÇÃO (Intacto)
  app:
    build: ./app_code
    container_name: vidaplus-app
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=vidaplus_db
      - DB_USER=root
      - DB_PASSWORD=admin

  # SERVIÇO 3: O TÚNEL CLOUDFLARE (NOVO!)
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      # IMPORTANTE: Apague o texto abaixo e cole seu Token gigante
      - TUNNEL_TOKEN=eyJhIjoiYjQ1MTU1MjdjNjI2MmZiNzUzZTRhMmYxODEwMTk0ZjciLCJ0IjoiMzFkODBmN2QtZmM0OS00MzhmLWE1NGYtY2FjNjQ3ODQzYTQyIiwicyI6Ik5qYzJNMk0wTURjdE5UbG1OeTAwTXpRMUxXRTNZV1l0TldNNU1HSXpNR0ZtTkRSaiJ9
	  
	# --- MONITORAMENTO ---
  prometheus:
	image: prom/prometheus:latest
	container_name: vidaplus-prometheus
	volumes:
	  - ./prometheus.yml:/etc/prometheus/prometheus.yml
  	ports:
	  - "9090:9090"
  	command:
	  - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
	image: grafana/grafana:latest
	container_name: vidaplus-grafana
	ports:
	  - "3000:3000"
	volumes:
	  - grafana_data:/var/lib/grafana
	environment:
	  - GF_SECURITY_ADMIN_PASSWORD=admin
	depends_on:
	  - prometheus
		  
volumes:
  grafana_data: