name: Deploy VidaPlus no ThinkPad

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Baixando código mais recente
      uses: actions/checkout@v3

    - name: Derrubando containers antigos
      run: docker compose down || true   # <--- SEM SUDO

    - name: Subindo nova versão (Rebuild)
      run: docker compose up -d --build  # <--- SEM SUDO

    - name: Limpeza de imagens velhas
      run: docker image prune -f         # <--- SEM SUDO