name: Deploy Automático no ThinkPad

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Baixar Código Novo
        uses: actions/checkout@v3

      - name: Atualizar Aplicação
        run: |
          # 1. Entra na pasta do projeto no ThinkPad
          cd /home/globaloficio/vidaplus-server
          
          # 2. Garante que temos a versão mais recente do código
          # (O git stash garante que mudanças locais não bloqueiem o pull)
          git stash
          git pull origin main
          
          # 3. Reconstrói e sobe os containers
          # O --build garante que o Java seja recompilado com o código novo
          docker compose up -d --build